# Phase 4: Modeling & Evaluation

## Group 3
- Jumanah Ibrahim
- Arwa Almutairi
- Dana Alturki
- Shatha Munif

In [20]:
# Import libraries
import pandas as pd
import numpy as np

# Upload dataset
df = pd.read_csv('diabetes_risk_dataset.csv')

# Display first rows
df.head()

,Patient_ID,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,1,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,2,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,3,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,4,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,5,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [21]:
#from google.colab import drive
#drive.mount('/content/drive')

## EDA Summary

In Phase 3, we explored the dataset and gained several important insights:

- The dataset contains 6000 rows and 19 columns.
- There were no missing values in the dataset.
- No duplicate records were found.
- The dataset includes both numerical and categorical features.
- The target variable (diabetes_risk_category) showed class imbalance, with more samples in the "Low Risk" category.

These insights guided our preprocessing steps in this phase.

## Data Preprocessing

Based on the EDA findings, we applied the following preprocessing steps:

- Removed unnecessary columns (e.g., Patient_ID)
- Converted categorical variables into numerical format
- Ensured the dataset is clean and suitable for machine learning models

In [22]:
# Remove ID column
df = df.drop('Patient_ID', axis=1)

# Convert categorical variables into numerical
df = pd.get_dummies(df, drop_first=True)

## Train-Test Split

In this step, we define the input features (X) and the target variable (y), then split the dataset into training and testing sets.

In [23]:
df = df.drop('diabetes_risk_score', axis=1)
#  improve performance of random forest

In [24]:
from sklearn.model_selection import train_test_split

# Define features and target
df['target'] = df[[
    'diabetes_risk_category_Low Risk',
    'diabetes_risk_category_Prediabetes'
]].idxmax(axis=1)

df['target'] = df['target'].str.replace('diabetes_risk_category_', '')

df = df.drop([
    'diabetes_risk_category_Low Risk',
    'diabetes_risk_category_Prediabetes'
], axis=1)

X = df.drop('target', axis=1)
y = df['target']


# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Check shapes
print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (4800, 17)
Testing set: (1200, 17)

The dataset was split into training and testing sets using an 80/20 ratio.

Stratified sampling was used to maintain the distribution of the target variable across both sets, ensuring fair model evaluation.

# Model trining

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Feature scaling was applied to improve model performance, especially for models like SVM and Logistic Regression which are sensitive to feature magnitudes

## 1) Logistic Regression

In [27]:
lr = LogisticRegression(max_iter=2000)
#Initialize

In [28]:
lr.fit(X_train, y_train)
#trianing

LogisticRegression(max_iter=2000)

In [29]:
y_pred_lr = lr.predict(X_test)
# Prediction

### 2)SVM

In [30]:
svm = SVC()
#Initialize

In [31]:
svm.fit(X_train, y_train)
#trianing

SVC()

In [32]:
y_pred_svm = svm.predict(X_test)
# Prediction

##  3) Random Forest

In [33]:
rf = RandomForestClassifier()
#Initialize

In [34]:
rf.fit(X_train, y_train)
#trianing

RandomForestClassifier()

In [35]:
y_pred_rf = rf.predict(X_test)
## Prediction

in this step, three machine learning models were implemented: Logistic Regression, Support Vector Machine (SVM), and Random Forest.
Each model was trained using the training dataset to learn patterns and relationships between the features and the target variable.
The trained models were then used to make predictions on the test dataset.

### 4) Evaluation & comparison

In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Logistic Regression
acc_lr = accuracy_score(y_test, y_pred_lr)
prec_lr = precision_score(y_test, y_pred_lr, average="weighted")
rec_lr = recall_score(y_test, y_pred_lr, average="weighted")
f1_lr = f1_score(y_test, y_pred_lr, average="weighted")

# SVM
acc_svm = accuracy_score(y_test, y_pred_svm)
prec_svm = precision_score(y_test, y_pred_svm, average="weighted")
rec_svm = recall_score(y_test, y_pred_svm, average="weighted")
f1_svm = f1_score(y_test, y_pred_svm, average="weighted")

# Random Forest
acc_rf = accuracy_score(y_test, y_pred_rf)
prec_rf = precision_score(y_test, y_pred_rf, average="weighted")
rec_rf = recall_score(y_test, y_pred_rf, average="weighted")
f1_rf = f1_score(y_test, y_pred_rf, average="weighted")

In [37]:
results = pd.DataFrame({
    "Model": ["Logistic Regression", "SVM", "Random Forest"],
    "Accuracy": [acc_lr, acc_svm, acc_rf],
    "Precision": [prec_lr, prec_svm, prec_rf],
    "Recall": [rec_lr, rec_svm, rec_rf],
    "F1-Score": [f1_lr, f1_svm, f1_rf]
})
results

                 Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression  0.810000   0.808109  0.810000  0.728947
1                  SVM  0.915000   0.921240  0.915000  0.917154
2        Random Forest  0.916667   0.915031  0.916667  0.915663

The Random Forest model initially achieved perfect accuracy, which indicated potential data leakage. After removing highly correlated features such as "diabetes_risk_score",the model performance became more realistic and reliable